[package]
name = "greego"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[features]
default = ["apple"]
apple = []


[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = { version = "2", features = ["colored"] }
surrealdb = { version = "2", features = ["kv-rocksdb", "kv-mem"] }
tokio = { version = "1.41.1", features = ["sync", "rt-multi-thread"] }
env_logger = "0.11.8"
anyhow = "1.0.100"
async-trait = "0.1"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "stream"] }
futures = "0.3"
async-stream = "0.3"

[profile.release]
lto = true
strip = true
opt-level = 3
panic = 'abort'
codegen-units = 1
